# ========================================
# FileName: lily58.conf
# Date: 07.06.2023 (original header preserved)
# Author: Marcos Chow Castro
# Email: mctechnology170318@gmail.com
# GitHub: https://github.com/mctechnology17
# Brief: configuration file for ZMK firmware (Lily58)
# Board: nice_nano_v2 and puchi_ble_v1
# =========================================

### Boost Bluetooth TX power, also make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

### POWER OPTIONS
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_EXT_POWER=y

### MOUSE
CONFIG_ZMK_MOUSE=y

### ZMK STUDIO
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# ================================
# Display core
# ================================
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Prevent display from starving key scan
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=5
# increased for RAW HID (use 3072 when RAW HID enabled)
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=3072

# Disable responsive widgets (critical)
CONFIG_NICE_OLED_WIDGET_RESPONSIVE=n
CONFIG_NICE_OLED_WIDGET_RESPONSIVE_BONGO_CAT=n

# ================================
# Speedometer (WPM gauge)
# ================================
CONFIG_NICE_OLED_WIDGET_SPEEDOMETER=y

# Place it in the same space the volume widget used
CONFIG_NICE_OLED_WIDGET_SPEEDOMETER_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_SPEEDOMETER_CUSTOM_Y=98
# Smooth out WPM updates (less jitter)
CONFIG_ZMK_WPM_LIVE_UPDATE_INTERVAL=500
CONFIG_ZMK_WPM_DECAY_RATE=15


# ================================
# Disable Bongo Cat everywhere
# ================================
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_BONGO_CAT=n

# ================================
# Peripheral animation (RIGHT)
# ================================
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n

# Slow animation to sane speed (milliseconds per frame)
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS=1500
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_X=18
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_Y=-18

### HID para nice!view ePaperDisplay
# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

### Improves compatibility with iPad
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
